import { createAudioPlayer, setAudioModeAsync, type AudioPlayer } from 'expo-audio';

// The web app synthesizes beeps on the fly via a Web Audio oscillator
// (AudioContext.createOscillator) — there's no equivalent for procedural
// tone synthesis in React Native, so we pre-rendered the 3 (freq, dur)
// pairs useTimer.ts actually calls beep() with as short WAV assets
// (see ../../assets/sounds, generated by a one-off script) and play the
// closest match here.
const TICK = require('../../assets/sounds/beep-tick.wav'); // 660Hz, 0.08s — countdown tick
const WORK = require('../../assets/sounds/beep-work.wav'); // 880Hz, 0.12s — step -> work
const REST = require('../../assets/sounds/beep-rest.wav'); // 440Hz, 0.12s — step -> rest/gap/prep

let players: { tick: AudioPlayer; work: AudioPlayer; rest: AudioPlayer } | null = null;

export function unlockAudio(): void {
  if (players) return;
  try {
    void setAudioModeAsync({ playsInSilentMode: true });
    players = {
      tick: createAudioPlayer(TICK),
      work: createAudioPlayer(WORK),
      rest: createAudioPlayer(REST),
    };
  } catch {
    // audio not supported — ignore
  }
}

function pick(freq: number): AudioPlayer | null {
  if (!players) return null;
  if (freq >= 770) return players.work; // ~880Hz
  if (freq >= 550) return players.tick; // ~660Hz
  return players.rest; // ~440Hz
}

export function beep(freq: number, _dur: number, muted: boolean): void {
  if (muted) return;
  const player = pick(freq);
  if (!player) return;
  try {
    player.seekTo(0);
    player.play();
  } catch {
    // playback error — ignore
  }
}
